GET http://localhost:3000/customer

###

GET http://localhost:3000/address

###

GET http://localhost:3000/customer/5f60db5e0b9ed40b541666be


###

POST http://localhost:3000/customer
Content-Type: application/json

{
"name": "James Brown", "email": "jamesbrown@test.com"
}

###

DELETE http://localhost:3000/customer/5f5a6b44010b0d277902b12f

###

PATCH http://localhost:3000/customer/5f5a6b44010b0d277902b12f
Content-Type: application/json

{
"name": "Adam James"
}

###

POST http://localhost:3000/customer/5f60db5e0b9ed40b541666be
Content-Type: application/json

{
"address": "Torrance, CA"
}