GET http://localhost:3000/customer

###

GET http://localhost:3000/customer/5f5a6b44010b0d277902b12f


###

POST http://localhost:3000/customer
Content-Type: application/json

{
"name": "Bob Dylan", "email": "bobdylan@test.com"
}

###

DELETE http://localhost:3000/customer/5f5a6b20010b0d277902b12e

###

PATCH http://localhost:3000/customer/5f5a6b44010b0d277902b12f
Content-Type: application/json

{
"name": "Adam James"
}

###

POST http://localhost:3000/customer/5f5a6b44010b0d277902b12f
Content-Type: application/json

{
"address": "111 Way, Hawaii"
}